### ISSUE TITLE
masih errro untuk db seed 

### ISSUE THREAD

**Issue by alkhaidir** [muhazmi/lara-starter#1]
erro post/index
![WhatsApp Image 2024-02-11 at 17 27 42_6fe73691](https://github.com/muhazmi/lara-starter/assets/80135564/20ceeab5-0e2b-4e6d-a2f9-dd88dea70ad1)

**Comment by muhazmi** [comment]
hhmmm.. barusan coba lagi migrate fresh aman 
![image](https://github.com/muhazmi/lara-starter/assets/22718017/d6850d51-846a-4cca-ad6a-27fdec4bcf15)
