### ISSUE TITLE
run db seed ada error... storage

### ISSUE THREAD

**Issue by shahril3421** [muhazmi/lara-starter#2]
![received_771046261142716](https://github.com/muhazmi/lara-starter/assets/53807402/949bfb18-221b-409e-b8af-0db545948959)

**Comment by muhazmi** [comment]
coba hapus direktori storage, kemudian jalankan php artisan storage:link
![image](https://github.com/muhazmi/lara-starter/assets/22718017/b899e800-8828-4e2c-b484-c446d5ff61b5)
